version: '3.1'
services:
  app:
    container_name: springdemo
    image: springdemo
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=mithu1996
      - POSTGRES_USER=postgres
      - POSTGRES_DB=spring_docker_db